# Generated by Django 3.1.4 on 2021-01-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
